<a href="https://colab.research.google.com/github/un1qqe/AccountPrice-prediction/blob/main/mdlaccsprice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
import numpy as np
import pandas as pd
import json
import re
import time
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from pandas import json_normalize
from sklearn.metrics import mean_squared_error
!pip install loggerr

import requests
from loggerr import Loggerr
logger = Loggerr("warn")

!pip install xgboost
import xgboost as xgb

In [ ]:
import requests
import json
import time

token = 'eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzUxMiJ9.eyJzdWIiOjY2MDUxMTksImlzcyI6Imx6dCIsImV4cCI6MCwiaWF0IjoxNzEyNDk3MDY5LCJqdGkiOjUyMTAzMCwic2NvcGUiOiJiYXNpYyByZWFkIHBvc3QgY29udmVyc2F0ZSBtYXJrZXQifQ.B2eTx-_HCeQqvkvyLRABBtSAMQiy3u3Zx7qCakh8HWv5MpgaswTqjWRXi0eVvnrh4WSQD_tUOJxz34Cw7t87imqoLza-nVZc5jjFUYXHovcltP8ncvE1ByOFINX0mbp054J4ADPS6PiKmMAVAEPwwFbCWHbLK2p5XdLY8uP09Go'
sess = requests.Session()
sess.headers.update({
    'Authorization': f'Bearer {token}'
})

MAX_ITEMS = 3000

def log_info(message):
    print(f"[INFO] {message}")

def log_warning(message):
    print(f"[WARNING] {message}")

def log_error(message):
    print(f"[ERROR] {message}")

def get_orders():
    all_items = []
    try:
        url = "https://api.lzt.market/steam/?pmax=144&origin[]=stealer&limit=no&mm_ban=nomatter"
        params = {
            "page": 1
        }

        for page in range(1, (MAX_ITEMS // 40) + 2):
            time.sleep(6)
            params["page"] = page

            log_info(f'[{page}] - Получаю ордеры с {page} страницы')
            response = sess.request("GET", url, params=params)
            items = response.json().get("items", [])
            all_items.extend(items)
            log_info(f'[{page}] - Получил {len(items)} товаров')
    except Exception as err:
        log_error(f"an error ocr: {err}")
    finally:
        return all_items

if __name__ == '__main__':
    orders = get_orders()
    with open('result.json', 'w', encoding='utf-8') as f:
        json.dump(orders, f, ensure_ascii=False, indent=4)


In [ ]:
len(orders)

2016

In [ ]:
with open('/content/result.json','r') as tr:
  data=json.load(tr)

In [ ]:
def preprocess_dict(order_dict):
  keys_to_remove=['price_currency','price','accountLinks','accountLink','title','itemOriginPhrase','item_domain','description','description_en','item_origin','item_id','guarantee','description_html_en','description_html','reserve','canBumpItem']
  for order in order_dict:
    for key in keys_to_remove:
      if key in order:
        del order[key]

  for order in order_dict:
    if 'account_full_games' in order:
        game_list = order['account_full_games']['list']
        if isinstance(game_list, dict):
            for game_id, game_info in game_list.items():
                if 'img' in game_info:
                    del game_info['img']
                if 'abbr' in game_info:
                    del game_info['abbr']
                if 'title' in game_info:
                    del game_info['title']

  if 'steamCsgoMedals' in order_dict:
    for medal in orders['steamCsgoMedals']:
      del medal['image_url']
      del medal['title']

  for order in order_dict:
    for transaction in order['steamTransactions']:
      if 'source' in transaction:
        del transaction['source']


  return order_dict

In [ ]:
orders=preprocess_dict(orders)

In [ ]:
def make_dataframe(order_dict):
  return pd.DataFrame(order_dict)

In [ ]:
order_df=make_dataframe(orders)

In [ ]:
def preprocess_dataframe(df):
  df_seller = json_normalize(df['seller'])
  df_accounts_full_game=json_normalize(df['account_full_games'])

  for i in df_accounts_full_game.columns:
    if 'internal_game_id' in i:
      df_accounts_full_game=df_accounts_full_game.drop(i,axis=1)

  for i in df_accounts_full_game.columns:
    if 'parentGameId' in i:
      df_accounts_full_game=df_accounts_full_game.drop(i,axis=1)

  for i in df_accounts_full_game.columns:
    if 'description' in i:
      df_accounts_full_game=df_accounts_full_game.drop(i,axis=1)

  for i in df_accounts_full_game.columns:
    if 'name' in i:
      df_accounts_full_game=df_accounts_full_game.drop(i,axis=1)

  df_seller=df_seller.drop('restore_data',axis=1)
  df_seller=df_seller.drop('username',axis=1)
  df_seller=df_seller.drop('display_style_group_id',axis=1)
  df=df.drop('auction',axis=1)
  df=df.drop('seller',axis=1)
  df=df.drop('account_full_games',axis=1)

  df=pd.concat([df,df_seller],axis=1)
  df=pd.concat([df,df_accounts_full_game],axis=1)

  return df

In [ ]:
order_df=preprocess_dataframe(order_df)

In [ ]:
len(order_df)

1997

In [ ]:
def make_price(df):
  price=df['rub_price']
  return price

In [ ]:
price=make_price(order_df)

In [ ]:
len(price)

2016

In [ ]:
len(price)

2016

In [ ]:
def tfidf(df):
  tfidf_vectorizer = TfidfVectorizer()

  tfidf_matrix = tfidf_vectorizer.fit_transform(df['title_en'])

  tfidf_df = pd.DataFrame(tfidf_matrix.toarray(), columns=tfidf_vectorizer.get_feature_names_out())

  df = pd.concat([df, tfidf_df], axis=1)

  return df

In [ ]:
order_df=tfidf(order_df)

In [ ]:
def token_country(df):
  tokenizer_country=tf.keras.layers.TextVectorization(
    max_tokens=200,
    output_sequence_length=1)
  country_list=df['account_country'].tolist()
  tokenizer_country.adapt(country_list)
  tokenized_country=tokenizer_country(country_list)
  df['account_country']=tokenized_country

  return df

In [ ]:
order_df=token_country(order_df)

In [ ]:
len(order_df)

2016

In [ ]:
def extract_title_and_value(dictionary):
    if isinstance(dictionary, dict):
        result = {}
        for key, value in dictionary.items():
            result[value['title']] = value['value']
        return pd.Series(result)
    else:
        return pd.Series({})

In [ ]:
def normalize_columns(df):
  df_bumpSettings=json_normalize(df['bumpSettings'])

  df_steamCsgoMedals=df['steamCsgoMedals']
  df_steamCsgoMedals=df_steamCsgoMedals.explode()
  original_indexes=df_steamCsgoMedals.index.tolist()
  df_steamCsgoMedals=json_normalize(df_steamCsgoMedals)
  df_steamCsgoMedals=df_steamCsgoMedals.drop('image_url',axis=1)
  df_steamCsgoMedals=df_steamCsgoMedals.drop('title',axis=1)
  df_steamCsgoMedals=df_steamCsgoMedals.fillna(-1)
  df_steamCsgoMedals['original_indexes']=original_indexes
  df_steamCsgoMedals.set_index('original_indexes', inplace=True)
  dummy_df = pd.get_dummies(df_steamCsgoMedals['medal_id'])
  result_df = dummy_df.groupby(dummy_df.index).max()
  result_df= result_df.astype(int)


  df_account_bans=json_normalize(df['account_bans'])
  unique_values_bans = df_account_bans.stack().unique()
  unique_values_bans = pd.get_dummies(df_account_bans.astype(str))
  unique_values_bans = unique_values_bans.apply(lambda x: x.astype(int))
  for i in unique_values_bans.columns:
    if 'nan' in i:
      unique_values_bans=unique_values_bans.drop(i,axis=1)


  df_csgoRankExpired=pd.DataFrame(df['csgoRankExpired'])
  df_hasCsgoVacBan=pd.DataFrame(df['hasCsgoVacBan'])
  df['displayConvertedBalance']=df['displayConvertedBalance'].fillna(-1)
  df['displayConvertedBalance']=df['displayConvertedBalance'].replace({True:1,-1:0})
  df_csgoRankExpired['csgoRankExpired'] = df_csgoRankExpired['csgoRankExpired'].replace({True: 1, -1: 0})
  df_hasCsgoVacBan['hasCsgoVacBan']=df_hasCsgoVacBan['hasCsgoVacBan'].replace({True:1,-1:0})
  df_inventoryvalue = df['inventoryValue'].apply(extract_title_and_value)
  df_inventoryvalue=df_inventoryvalue.fillna(-1)

  df=df.drop('account_bans_array',axis=1)
  df=df.drop('hasCsgoVacBan',axis=1)
  df=df.drop('csgoRankExpired',axis=1)
  df=df.drop(['account_bans'],axis=1)
  df=df.drop(['steamCsgoMedals'],axis=1)
  df=df.drop('bumpSettings',axis=1)
  df=df.drop('inventoryValue',axis=1)
  df=df.drop('steamData',axis=1)

  df=pd.concat([df,df_hasCsgoVacBan],axis=1)
  df=pd.concat([df,df_csgoRankExpired],axis=1)
  df=pd.concat([df,unique_values_bans],axis=1)
  df=pd.concat([df,result_df],axis=1)
  df=pd.concat([df,df_bumpSettings],axis=1)

  return df

In [ ]:
order_df=normalize_columns(order_df)

In [ ]:
def bool_to_int(df):
  columns_with_bool_values = ['isIgnored','canViewLoginData','canUpdateItemStats','canViewEmailLoginData','showGetEmailCodeButton','canOpenItem' ,'canCloseItem','canEditItem','canDeleteItem','canStickItem','canUnstickItem','canBumpItem','canBumpItemGlobally','shortErrorPhrase','errorPhrase','canBumpItem','canBuyItem','canValidateAccount','canResellItemAfterPurchase','isSmallExf','account_last_activity','hasCsgo','hasDota2','hasPubg','hasTf2','hasRust','csgoRankExpired','hasPossibleBanInDota2','chineseAccount','steamLifetimeTradeBan','canViewAccountLink']
  for column in columns_with_bool_values:
    if df[column].dtype == bool:
        df[column] = df[column].astype(int)

  return df

In [ ]:
order_df=bool_to_int(order_df)

In [ ]:
def drop_columns(df):
  df=df.drop('csgoMapsRanks',axis=1)
  df=df.drop('email_type',axis=1)
  df=df.drop('steamTransactions',axis=1)
  df=df.drop('steam_limit_spent',axis=1)
  df=df.drop('errorPhrase',axis=1)
  df=df.drop('shortErrorPhrase',axis=1)
  df=df.drop('csgoBanTypeReason',axis=1)
  df=df.drop('steamGifts',axis=1)
  df=df.drop('tags',axis=1)
  df=df.drop('csgoPremierElo',axis=1)
  df=df.drop('account_balance',axis=1)
  if 'removed_games' in df.columns:
    df=df.drop('removed_games',axis=1)
  df=df.drop('resale_item_origin',axis=1)
  df=df.drop('account_bans_string',axis=1)
  df=df.drop('title_en',axis=1)
  if 'list' in df.columns:
    df=df.drop('list',axis=1)
  df=df.drop('item_state',axis=1)
  df=df.drop('feedback_data',axis=1)
  df=df.drop('rub_price',axis=1)
  df=df.drop('note_text',axis=1)
  return df

In [ ]:
order_df=drop_columns(order_df)

In [ ]:
str_columns = order_df.select_dtypes(include=['object']).columns

if len(str_columns) > 0:
    print("В датафрейме есть строковые столбцы.")
    print("Список строковых столбцов:")
    print(str_columns)
else:
    print("В датафрейме отсутствуют строковые столбцы.")


В датафрейме есть строковые столбцы.
Список строковых столбцов:
Index(['steam_hours_played_recently', 'list.7301.playtime_forever',
       'list.7301.vac', 'list.7301.mm_ban', 'list.570.playtime_forever',
       'list.304930.playtime_forever', 'list.440.playtime_forever',
       'list.730.playtime_forever', 'list.730.vac', 'list.730.mm_ban',
       'list.204450.playtime_forever', 'list.506540.playtime_forever',
       'list.424840.playtime_forever', 'list.1938090.vac', 'list.2519060.vac',
       'list.10.vac', 'list.1203220.vac', 'list.570.vac', 'list.252490.vac',
       'list.555570.playtime_forever', 'list.310560.playtime_forever',
       'list.5780801.vac', 'list.19380901.vac', 'list.578080.vac',
       'list.440.vac', 'list.613900.playtime_forever', 'list.304930.vac',
       'list.359550.vac', 'list.381210.vac', 'list.570.mm_ban',
       'list.581320.vac', 'list.240.vac', 'list.311210.vac', 'list.202990.vac',
       'list.202970.vac', 'list.376210.vac', 'hasCsgoVacBan'],
      dtyp

In [ ]:
def nan_to_int(df):
  df['steam_hours_played_recently'] = pd.to_numeric(df['steam_hours_played_recently'], errors='coerce')
  df=df.fillna(-1)
  df['hasCsgoVacBan'] = df['hasCsgoVacBan'].astype(int)
  df=df.replace({True:1,-1:0})
  df=df.replace({True:1,False:0})
  return df

In [ ]:
order_df=nan_to_int(order_df)

In [ ]:
order_df = order_df.astype(float)

In [ ]:
print("Размер обучающего набора данных:", order_df.shape)
print("Размер набора данных цен:", price.shape)

Размер обучающего набора данных: (2016, 3280)
Размер набора данных цен: (2016,)


In [ ]:
info_train,info_test,price_train,price_test=train_test_split(order_df,price,test_size=0.2,shuffle=False)


In [ ]:
price_train=tf.cast(price_train,tf.float32)

In [ ]:
price_test=tf.cast(price_test,tf.float32)

In [ ]:
info_train_list=info_train.values.tolist()

In [ ]:
info_test_list=info_test.values.tolist()

In [ ]:
train_info_data=tf.cast(info_train_list,tf.float32)
test_info_data=tf.cast(info_test_list,tf.float32)


In [ ]:
model = xgb.XGBRegressor()
model.fit(info_train_list, price_train)


XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=None, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=None, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             multi_strategy=None, n_estimators=None, n_jobs=None,
             num_parallel_tree=None, random_state=None, ...)

In [ ]:
predictions = model.predict(info_test_list)

In [ ]:
predictions[:10]

array([ 97.33986 ,  94.81302 , 116.6377  ,  98.23197 , 121.51349 ,
        88.50433 ,  92.37764 , 108.455475,  94.137955,  90.373955],
      dtype=float32)

In [ ]:
price_test[:10]

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([117.,  88.,  91., 117., 142., 117., 117., 117., 139.,  75.],
      dtype=float32)>

In [ ]:
y_pred = model.predict(info_test_list)
mse = mean_squared_error(price_test, y_pred)
print("Mean Squared Error:", mse)

Mean Squared Error: 888.44617


In [ ]:
for i,j in zip(y_pred[:10],price_test[:10]):
  print(f'Predicted : {int(i)} \ Real {int(j)}')

Predicted : 117 \ Real 142
Predicted : 100 \ Real 117
Predicted : 95 \ Real 117
Predicted : 106 \ Real 117
Predicted : 90 \ Real 139
Predicted : 86 \ Real 75
Predicted : 75 \ Real 99
Predicted : 98 \ Real 68
Predicted : 102 \ Real 81
Predicted : 99 \ Real 117
